// ============================================================
// CELESTIS CONCLAVE — SITE DATA STORE
// Auto-generated by Admin CMS — 2026-03-17T16:42:13.671Z
// ============================================================

const SITE_DATA = {
  "announcement": {
    "active": true,
    "message": "🌟 Applications for the 2026-27 Cohort are now open! Join the Conclave today!",
    "link": "./contact.html",
    "linkText": "Apply Now"
  },
  "sponsors": [],
  "team": [
    {
      "id": 1,
      "name": "Maalvikaa Sharma",
      "role": "President",
      "bio": "Maalvikaa Sharma is the President of Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 2,
      "name": "Rishit Choudhary",
      "role": "Director of Mentorship & STEM Mentor",
      "bio": "Rishit Choudhary is the Director of Mentorship and a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 3,
      "name": "Raunak Taneja",
      "role": "STEM Mentor",
      "bio": "Raunak Taneja is a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 4,
      "name": "Ranveer Gokulgandhi",
      "role": "STEM Mentor",
      "bio": "Ranveer Gokulgandhi is a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 5,
      "name": "Svanik Ghai",
      "role": "STEM Mentor & Outreach Associate",
      "bio": "Svanik Ghai is a STEM Mentor and Outreach Associate for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 6,
      "name": "Khwaish Garg",
      "role": "Operations Coordinator & STEM Mentor",
      "bio": "Khwaish Garg is the Operations Coordinator and a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 7,
      "name": "Anya Aggarwal",
      "role": "STEM Mentor",
      "bio": "Anya Aggarwal is a STEM Mentor for Celestis Conclave",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 8,
      "name": "Myraa Khanna",
      "role": "Event Coordinator & STEM Mentor",
      "bio": "Myraa Khanna is an Event Coordinator and a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 9,
      "name": "Aadhya Baid",
      "role": "Director of Operations & Communications Associate",
      "bio": "Aadhya Baid is the Director of Operations and a Communications Associate for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 10,
      "name": "Tuhinn Mishra",
      "role": "Event Coordinator",
      "bio": "Tuhinn Mishra is an Event Coordinator for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 11,
      "name": "Kyra Hamrapurkar",
      "role": "Event Coordinator",
      "bio": "Kyra Hamrapurkar is an Event Coordinator for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 12,
      "name": "Incia Chadha",
      "role": "Director for Communications & Outreach",
      "bio": "Incia Chadha is the Director for Communications & Outreach for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 13,
      "name": "Zoya Borkataky",
      "role": "Graphics Designer",
      "bio": "Zoya Borkataky is a Graphics Designer for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    }
  ],
  "projects": [
    {
      "id": 1,
      "title": "AstroScope — DIY Radio Telescope",
      "image": "assets/images/projects/1773660879254-orion.png",
      "shortDesc": "A fully functional radio telescope built from salvaged satellite dishes and custom SDR hardware, capable of detecting Jupiter's radio emissions.",
      "longDesc": "AstroScope began as a thought experiment: could a group of undergraduates build a radio telescope on a shoestring budget? The answer, it turns out, is yes.\n\nUsing two salvaged C-band satellite dishes, a software-defined radio (SDR) dongle, and custom low-noise amplifiers we designed ourselves, we constructed a basic interferometric radio telescope. The system is capable of detecting the 20.1 MHz radio emissions from Jupiter, as well as mapping the galactic plane in the 21 cm hydrogen line.\n\nThe signal processing pipeline is written entirely in Python, using GNU Radio for the DSP backend. We also developed a web-based visualiser to display live waterfall plots and sky maps. The entire project, from hardware to software, is open-source.",
      "tags": [
        "Astronomy",
        "Hardware",
        "Python",
        "RF Engineering"
      ],
      "link": "#",
      "featured": true
    },
    {
      "id": 2,
      "title": "ChemSim — Molecular Dynamics Visualiser",
      "image": "assets/images/projects/chemsim.jpg",
      "shortDesc": "An interactive browser-based simulation of molecular dynamics using WebGL, allowing students to visualise intermolecular forces in real time.",
      "longDesc": "ChemSim was born out of frustration with static textbook diagrams. Intermolecular forces are fundamentally dynamic — so why are they always shown as frozen arrows?\n\nBuilt with Three.js and a custom Verlet integration engine, ChemSim lets users place molecules in a 2D or 3D simulation space and watch them interact. Lennard-Jones potentials govern the van der Waals forces, while a simplified electrostatics model handles dipole interactions.\n\nThe tool is now used in several undergraduate chemistry courses as a supplementary visualisation aid. Future work includes adding solvent effects and a proper quantum mechanical Hamiltonian for small molecules.",
      "tags": [
        "Chemistry",
        "WebGL",
        "Three.js",
        "Simulation"
      ],
      "link": "https://celestis.github.io/chemsim",
      "featured": true
    },
    {
      "id": 3,
      "title": "BioMap — Biodiversity Monitoring Network",
      "image": "assets/images/projects/biomap.jpg",
      "shortDesc": "A network of low-cost acoustic sensors deployed across the campus to monitor biodiversity using machine learning classifiers.",
      "longDesc": "BioMap is an ongoing citizen-science project that turns our campus into a living laboratory. We deployed a network of 12 Raspberry Pi-based acoustic sensors across different ecosystems on campus — forest patches, wetlands, and open fields.\n\nEach sensor records ambient audio continuously, and a TensorFlow Lite model running on-device classifies bird calls, frog choruses, and insect stridulations in real time. The data is aggregated on a central server and visualised on an interactive map that anyone can access.\n\nThe project has so far identified 47 distinct bird species and 12 frog species on campus. The dataset is being shared with the local forest department for conservation planning.",
      "tags": [
        "Biology",
        "Machine Learning",
        "IoT",
        "Python"
      ],
      "link": "https://github.com/celestis/biomap",
      "featured": true
    },
    {
      "id": 4,
      "title": "CryptoLab — Visualising Encryption Algorithms",
      "image": "assets/images/projects/cryptolab.jpg",
      "shortDesc": "Step-by-step visual walkthroughs of AES, RSA, and elliptic curve cryptography, designed for students encountering these algorithms for the first time.",
      "longDesc": "Cryptography courses are notorious for losing students at the point where abstract algebra meets computer science. CryptoLab is our answer to this problem.\n\nThe tool provides animated, step-by-step visualisations of how AES encryption transforms data through its rounds of substitution, permutation, and mixing. For RSA, users can input their own primes (small ones!) and watch the key generation and encryption process unfold. The elliptic curve module visualises point addition and scalar multiplication geometrically.\n\nAll visualisations are built with D3.js and run entirely in the browser. The project has been well-received by several cryptography instructors who use it as a lecture aid.",
      "tags": [
        "Cryptography",
        "Mathematics",
        "D3.js",
        "Education"
      ],
      "link": "https://celestis.github.io/cryptolab",
      "featured": false
    },
    {
      "id": 5,
      "title": "SolarTrack — Smart Solar Panel Controller",
      "image": "assets/images/projects/solartrack.jpg",
      "shortDesc": "A dual-axis solar tracking system using stepper motors and a PID controller, increasing panel efficiency by up to 35% compared to fixed mounting.",
      "longDesc": "Fixed solar panels miss a significant fraction of available irradiance because the sun's position changes throughout the day. SolarTrack solves this with a dual-axis tracking mount that follows the sun from dawn to dusk.\n\nThe controller is built around an Arduino Mega, with a pair of stepper motors driving elevation and azimuth axes. Rather than using a photo-sensor array (which struggles on cloudy days), we implemented an astronomical algorithm that calculates the sun's position based on GPS coordinates and time, giving reliable tracking regardless of weather.\n\nA PID controller smooths out the tracking motion and prevents oscillation. Testing over three months showed a 35% increase in energy yield compared to a fixed panel of identical specification.",
      "tags": [
        "Electronics",
        "Arduino",
        "Control Systems",
        "Renewable Energy"
      ],
      "link": "https://github.com/celestis/solartrack",
      "featured": false
    }
  ],
  "articles": [
    {
      "id": 1,
      "title": "The Unreasonable Effectiveness of Fourier Transforms",
      "author": "Priya Sharma",
      "date": "2024-11-15",
      "coverImage": "assets/articles/images/fourier.jpg",
      "tags": [
        "Mathematics",
        "Signal Processing",
        "Physics"
      ],
      "preview": "From JPEG compression to MRI machines, one elegant mathematical idea underpins more of modern technology than almost anything else. Here's why.",
      "mdFile": "assets/articles/md/fourier-transforms.md",
      "featured": true
    },
    {
      "id": 2,
      "title": "Building a Quantum Circuit Simulator in Python",
      "author": "Aryan Mehta",
      "date": "2024-10-28",
      "coverImage": "assets/articles/images/quantum.jpg",
      "tags": [
        "Quantum Computing",
        "Python",
        "Tutorial"
      ],
      "preview": "Quantum computing doesn't require exotic hardware to start exploring. In this tutorial, we build a fully functional statevector simulator from scratch using only NumPy.",
      "mdFile": "assets/articles/md/quantum-simulator.md",
      "featured": true
    },
    {
      "id": 3,
      "title": "Dark Matter: What We Know, What We Don't, and Why It Matters",
      "author": "Aisha Khan",
      "date": "2024-10-10",
      "coverImage": "assets/articles/images/dark-matter.jpg",
      "tags": [
        "Astrophysics",
        "Physics",
        "Research"
      ],
      "preview": "We have compelling evidence that 85% of the matter in the universe is invisible. A survey of the evidence, the candidates, and the ongoing hunt.",
      "mdFile": "assets/articles/md/dark-matter.md",
      "featured": false
    },
    {
      "id": 4,
      "title": "Why Your Machine Learning Model is Probably Overfit",
      "author": "Rohan Verma",
      "date": "2024-09-22",
      "coverImage": "assets/articles/images/overfitting.jpg",
      "tags": [
        "Machine Learning",
        "Statistics",
        "Tutorial"
      ],
      "preview": "Overfitting is the silent killer of ML projects. Understanding the bias-variance tradeoff is the first step to building models that actually generalise.",
      "mdFile": "assets/articles/md/overfitting.md",
      "featured": false
    },
    {
      "id": 5,
      "title": "A Brief History of the Laser",
      "author": "Dev Patel",
      "date": "2024-09-05",
      "coverImage": "assets/articles/images/laser.jpg",
      "tags": [
        "Physics",
        "History of Science",
        "Optics"
      ],
      "preview": "From Einstein's 1917 prediction of stimulated emission to the femtosecond lasers of today, the story of the laser is a masterclass in the interplay between theory and experiment.",
      "mdFile": "assets/articles/md/laser-history.md",
      "featured": false
    }
  ],
  "resources": [
    {
      "id": 1,
      "title": "3Blue1Brown — Essence of Linear Algebra",
      "tags": [
        "Mathematics",
        "Linear Algebra",
        "Video Series"
      ],
      "description": "Grant Sanderson's legendary series builds geometric intuition for linear transformations, eigenvectors, and more. Essential viewing for anyone who has only encountered linear algebra through dry calculation.",
      "link": "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
      "category": "Video"
    },
    {
      "id": 2,
      "title": "MIT OpenCourseWare — Introduction to Algorithms",
      "tags": [
        "Computer Science",
        "Algorithms",
        "Course"
      ],
      "description": "MIT's 6.006 course, freely available with lecture videos, notes, and problem sets. Covers sorting, hashing, graph algorithms, and dynamic programming with rigour.",
      "link": "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/",
      "category": "Course"
    },
    {
      "id": 3,
      "title": "The Feynman Lectures on Physics",
      "tags": [
        "Physics",
        "Classical Mechanics",
        "Electromagnetism",
        "Quantum Mechanics"
      ],
      "description": "Feynman's three-volume masterpiece, now freely available online in its entirety. Covers all of undergraduate physics with unparalleled clarity and physical intuition.",
      "link": "https://www.feynmanlectures.caltech.edu/",
      "category": "Book"
    },
    {
      "id": 4,
      "title": "Brilliant.org — Interactive STEM Courses",
      "tags": [
        "Mathematics",
        "Physics",
        "Computer Science",
        "Interactive"
      ],
      "description": "Problem-driven learning covering mathematics, physics, and CS. Particularly strong for developing intuition through active problem-solving rather than passive reading.",
      "link": "https://brilliant.org",
      "category": "Platform"
    },
    {
      "id": 5,
      "title": "arXiv — Open Access Research Papers",
      "tags": [
        "Research",
        "Physics",
        "Mathematics",
        "CS",
        "Biology"
      ],
      "description": "The preprint server where most physics, mathematics, and CS research is posted before (and often instead of) formal publication. Essential for staying current with the field.",
      "link": "https://arxiv.org",
      "category": "Research"
    },
    {
      "id": 6,
      "title": "Paul's Online Math Notes",
      "tags": [
        "Mathematics",
        "Calculus",
        "Differential Equations",
        "Algebra"
      ],
      "description": "Comprehensive, well-written notes on Calculus I–III, Differential Equations, and Linear Algebra. Excellent for revision and filling gaps in understanding.",
      "link": "https://tutorial.math.lamar.edu/",
      "category": "Notes"
    },
    {
      "id": 7,
      "title": "Khan Academy — Science & Mathematics",
      "tags": [
        "Mathematics",
        "Physics",
        "Chemistry",
        "Biology",
        "Beginner"
      ],
      "description": "Freely accessible, well-structured lessons from secondary level through early undergraduate. Best used as a first introduction or for rapid revision of foundational material.",
      "link": "https://www.khanacademy.org/",
      "category": "Platform"
    },
    {
      "id": 8,
      "title": "Circuit Simulator — Falstad",
      "tags": [
        "Electronics",
        "Circuit Design",
        "Interactive",
        "Tool"
      ],
      "description": "A surprisingly powerful browser-based circuit simulator. Build and test circuits interactively, with real-time oscilloscope displays. Great for understanding circuit behaviour intuitively.",
      "link": "https://www.falstad.com/circuit/",
      "category": "Tool"
    }
  ]
};

if (typeof module !== 'undefined') module.exports = SITE_DATA;
