// ============================================================
// CELESTIS CONCLAVE — SITE DATA STORE
// Auto-generated by Admin CMS — 2026-03-26T05:28:58.607Z
// ============================================================

const SITE_DATA = {
  "announcement": {
    "active": true,
    "message": "🌟 Applications for the 2026-27 Cohort are now open! Join the Conclave today!",
    "link": "./contact.html",
    "linkText": "Apply Now"
  },
  "sponsors": [],
  "team": [
    {
      "id": 1,
      "name": "Maalvikaa Sharma",
      "role": "President",
      "bio": "Maalvikaa Sharma is the President of Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 2,
      "name": "Rishit Choudhary",
      "role": "Director of Mentorship & STEM Mentor",
      "bio": "Rishit Choudhary is the Director of Mentorship and a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 3,
      "name": "Raunak Taneja",
      "role": "STEM Mentor",
      "bio": "Raunak Taneja is a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 4,
      "name": "Ranveer Gokulgandhi",
      "role": "STEM Mentor",
      "bio": "Ranveer Gokulgandhi is a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 5,
      "name": "Svanik Ghai",
      "role": "STEM Mentor & Outreach Associate",
      "bio": "Svanik Ghai is a STEM Mentor and Outreach Associate for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 6,
      "name": "Khwaish Garg",
      "role": "Operations Coordinator & STEM Mentor",
      "bio": "Khwaish Garg is the Operations Coordinator and a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 7,
      "name": "Anya Aggarwal",
      "role": "STEM Mentor",
      "bio": "Anya Aggarwal is a STEM Mentor for Celestis Conclave",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 8,
      "name": "Myraa Khanna",
      "role": "Event Coordinator & STEM Mentor",
      "bio": "Myraa Khanna is an Event Coordinator and a STEM Mentor for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 9,
      "name": "Aadhya Baid",
      "role": "Director of Operations & Communications Associate",
      "bio": "Aadhya Baid is the Director of Operations and a Communications Associate for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 10,
      "name": "Tuhinn Mishra",
      "role": "Event Coordinator",
      "bio": "Tuhinn Mishra is an Event Coordinator for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 11,
      "name": "Kyra Hamrapurkar",
      "role": "Event Coordinator",
      "bio": "Kyra Hamrapurkar is an Event Coordinator for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 12,
      "name": "Incia Chadha",
      "role": "Director for Communications & Outreach",
      "bio": "Incia Chadha is the Director for Communications & Outreach for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    },
    {
      "id": 13,
      "name": "Zoya Borkataky",
      "role": "Graphics Designer",
      "bio": "Zoya Borkataky is a Graphics Designer for Celestis Conclave.",
      "socials": {
        "email": null,
        "phone": null
      },
      "photo": "assets/images/team/placeholder.jpg"
    }
  ],
  "projects": [
    {
      "id": 1,
      "title": "The Celestis Conclave Opening Event",
      "image": "assets/images/projects/opening-event.png",
      "shortDesc": "Our opening event is a STEM challenge where participants apply mathematics, science, and programming to solve realistic scientific problems. Participants build models, simulate systems, and present innovative solutions, with top teams advancing to a panel discussion on broader scientific and ethical issues.",
      "mdFile": "assets/projects/md/opening-event.md",
      "tags": [
        "Maths",
        "Physics",
        "Astronomy",
        "Computer Science"
      ],
      "link": "#",
      "featured": true
    }
  ],
  "articles": [
    {
      "id": 1,
      "title": "Why the Sky Appears Blue: On Rayleigh Scattering",
      "author": "Rishit Choudhary",
      "date": "2026-03-17",
      "coverImage": "assets/articles/images/why-the-sky-appears-blue.jpg",
      "tags": [
        "Physics",
        "Optics",
        "Light",
        "Atmosphere",
        "Natural Phenomena"
      ],
      "preview": "The scientific answer to our childhood question—why is the sky blue?",
      "mdFile": "assets/articles/md/why-the-sky-appears-blue.md",
      "featured": true
    }
  ],
  "resources": [
    {
      "id": 1,
      "title": "3Blue1Brown — Essence of Linear Algebra",
      "tags": [
        "Mathematics",
        "Linear Algebra",
        "Video Series"
      ],
      "description": "Grant Sanderson's legendary series builds geometric intuition for linear transformations, eigenvectors, and more. Essential viewing for anyone who has only encountered linear algebra through dry calculation.",
      "link": "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
      "category": "Video"
    },
    {
      "id": 2,
      "title": "MIT OpenCourseWare — Introduction to Algorithms",
      "tags": [
        "Computer Science",
        "Algorithms",
        "Course"
      ],
      "description": "MIT's 6.006 course, freely available with lecture videos, notes, and problem sets. Covers sorting, hashing, graph algorithms, and dynamic programming with rigour.",
      "link": "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/",
      "category": "Course"
    },
    {
      "id": 3,
      "title": "The Feynman Lectures on Physics",
      "tags": [
        "Physics",
        "Classical Mechanics",
        "Electromagnetism",
        "Quantum Mechanics"
      ],
      "description": "Feynman's three-volume masterpiece, now freely available online in its entirety. Covers all of undergraduate physics with unparalleled clarity and physical intuition.",
      "link": "https://www.feynmanlectures.caltech.edu/",
      "category": "Book"
    },
    {
      "id": 4,
      "title": "Brilliant.org — Interactive STEM Courses",
      "tags": [
        "Mathematics",
        "Physics",
        "Computer Science",
        "Interactive"
      ],
      "description": "Problem-driven learning covering mathematics, physics, and CS. Particularly strong for developing intuition through active problem-solving rather than passive reading.",
      "link": "https://brilliant.org",
      "category": "Platform"
    },
    {
      "id": 5,
      "title": "arXiv — Open Access Research Papers",
      "tags": [
        "Research",
        "Physics",
        "Mathematics",
        "CS",
        "Biology"
      ],
      "description": "The preprint server where most physics, mathematics, and CS research is posted before (and often instead of) formal publication. Essential for staying current with the field.",
      "link": "https://arxiv.org",
      "category": "Research"
    },
    {
      "id": 6,
      "title": "Paul's Online Math Notes",
      "tags": [
        "Mathematics",
        "Calculus",
        "Differential Equations",
        "Algebra"
      ],
      "description": "Comprehensive, well-written notes on Calculus I–III, Differential Equations, and Linear Algebra. Excellent for revision and filling gaps in understanding.",
      "link": "https://tutorial.math.lamar.edu/",
      "category": "Notes"
    },
    {
      "id": 7,
      "title": "Khan Academy — Science & Mathematics",
      "tags": [
        "Mathematics",
        "Physics",
        "Chemistry",
        "Biology",
        "Beginner"
      ],
      "description": "Freely accessible, well-structured lessons from secondary level through early undergraduate. Best used as a first introduction or for rapid revision of foundational material.",
      "link": "https://www.khanacademy.org/",
      "category": "Platform"
    },
    {
      "id": 8,
      "title": "Circuit Simulator — Falstad",
      "tags": [
        "Electronics",
        "Circuit Design",
        "Interactive",
        "Tool"
      ],
      "description": "A surprisingly powerful browser-based circuit simulator. Build and test circuits interactively, with real-time oscilloscope displays. Great for understanding circuit behaviour intuitively.",
      "link": "https://www.falstad.com/circuit/",
      "category": "Tool"
    }
  ]
};

if (typeof module !== 'undefined') module.exports = SITE_DATA;
